Add MOHS Rating
vEnhance/otis-web pull request #174
Opened 2023-02-08 19:35 UTC by Incompleteusern

![image](https://user-images.githubusercontent.com/58920010/217633209-f616e4ed-ec79-415a-8392-02d5b2249d9f.png)
![image](https://user-images.githubusercontent.com/58920010/217633247-531357ec-5a52-4f9f-a6bd-341a959bcfda.png)

2023-02-08 21:00 UTC, Incompleteusern commented
This has been rebranded as niceness

2023-02-08 21:25 UTC, vEnhance commented on arch/models.py
> +        validators=[MaxValueValidator(50)],
should be out of 10 right?

2023-02-08 21:25 UTC, vEnhance commented on arch/models.py
> +        votes = self.vote_set.all()
might want to add a type hint for `vote_set` into the `Problem` class so this doesn't fail the type check

2023-02-08 21:25 UTC, vEnhance commented on arch/models.py
> +            total /= len(votes)
i would rather just `return round(total / len(votes), 2)` here, shorter and doesn't cause a type clash

2023-02-08 21:36 UTC, vEnhance commented on arch/models.py
> +        validators=[MaxValueValidator(50)],
shouldn't this be a small positive integer field actually? rather than a floatfield

right now -9000.1434 is a valid input

2023-02-09 21:25 UTC, vEnhance commented on arch/models.py
> +            total /= len(votes)
aren't you dividing by len(votes) twice now?

seems like you should move the subsequent `        return round(total / len(votes), 2)` here and just delete this line

2023-02-09 21:26 UTC, vEnhance requested changes
Looks mostly fine, just `len(votes)` divided twice I think

2023-02-09 22:35 UTC, vEnhance approved these changes

2023-02-09 22:46 UTC, vEnhance commented
I merged in the recent `main` push and did some cleanup:

- I still think the division code was needlessly complicated, so I rewrote it in 7361f22.
- The `VoteForm` seemed completely useless to me? As far as I can tell it is never used, and the type hint should be `BaseModelForm[Vote]`. See b2a4b87.

Can you sanity-check these for me and test that things still work as intended on your local dev?

2023-02-09 22:49 UTC, vEnhance commented
I'm also going to add `created_at` and `updated_at` so that I have some semblance of time tracking (I think looking back I really should have these by default on every model that's editable by users).

2023-02-09 22:52 UTC, Incompleteusern commented
still seems to work as intended

2023-02-09 22:54 UTC, vEnhance commented
Cool, thanks.

2023-02-09 22:54 UTC, merged