upcoming markets/hanabi seeds
vEnhance/otis-web pull request #293
Opened 2023-08-29 05:42 UTC by waystern

current progress

made markets starting within 4 days visible and hanabi seeds starting within a month visible

markets show the slug currently for both student and staff view will change the staff view to be like the others with link and all

2023-08-31 15:39 UTC, vEnhance requested changes
Generally looks really solid. Thanks much.

I left some small feedback. We should also update `hanabicontest_list.html` with the upcoming changes, I think this should be pretty simple, above lines 67-69 add a new case for upcoming contests and hide the variant name/links.

Right now the code doesn't pass the style test. Run `black .` from the root directory of the project and it will autoformat the files so that check passes.

2023-08-31 15:39 UTC, vEnhance commented on hanabi/views.py
> +        return HanabiContest.upcoming.get_queryset()
I think this should be `return HanabiContest.upcoming.all()`

2023-08-31 15:39 UTC, vEnhance commented on markets/models.py
> +        return timezone.now() < self.start_date and timezone.now()+timedelta(days=7) >= self.start_date
Let's contract this to `timezone.now() < self.start_date < timezone.now() + timedelta(days=7)`, easier to read and shorter

2023-08-31 15:39 UTC, vEnhance commented on markets/templates/markets/market_list.html
> +            {{ market.slug }}
I think the slug may still leak info, can we put "Starts {{ market.start_date }}" here instead?

2023-08-31 17:07 UTC, waystern commented
@vEnhance sounds good. this was just so you could see my progress not a final product

I’ll make your suggested changes later today when I can get on my laptop

2023-08-31 23:30 UTC, vEnhance approved these changes

2023-08-31 23:34 UTC, vEnhance requested changes
Great!

Run `djlint` on the templates (or just run `autofix.sh`) to pass that style check, and change a couple of the colors to be consistent between the templates (maybe we can do warning/yellow for upcoming, success/green for active, primary/blue for past as the standard).

2023-08-31 23:34 UTC, vEnhance commented on hanabi/templates/hanabi/hanabicontest_list.html
> +            <td class="table-primary">Starts in {{ contest.start_date }}</td>
Can we flip the colors so that the upcoming is colored by `warning` and the active is colored by `primary`? (Right now it's vice-versa.)

2023-08-31 23:34 UTC, vEnhance commented on markets/templates/markets/market_list.html
> +      <tr class="{% if market.is_upcoming %}table-primary{% elif not market.has_started %}table-warning{% elif not market.has_ended %}table-success{% endif %}">
Again I think colors should be flipped here; upcoming is better as yellow imo

maybe make this consistent with the markets template too

2023-09-01 00:16 UTC, vEnhance approved these changes

2023-09-01 00:18 UTC, merged